aksbyocni:
  enabled: true
bpf:
  masquerade: true
hubble:
  enabled: true
  listenAddress: :4244
  metrics:
    enabled:
      - dns
      - drop:sourceContext=pod-short;destinationContext=pod-short
      - icmp
      - port-distribution
      - tcp
    port: 29091
  relay:
    enabled: true
  tls:
    auto:
      method: cronJob
  ui:
    enabled: true
kubeProxyReplacement: "true"
nodeinit:
  enabled: true
  restartPods: true
prometheus:
  enabled: true
  port: 29090
operator:
  prometheus:
    enabled: true
    port: 6942